---
- name: Set system cmd history
  lineinfile:
    path: /etc/profile
    line: '{{ item }}'
  with_items:
    - 'export HISTSIZE=9999999'
    - 'export HISTFILESIZE=9999999'
  tags: cmd_history

- name: Source system cmd history
  shell: source /etc/profile
  tags: cmd_history
